language: c

dist: bionic

branchs:
only:
  - master
   
before_install:
  - sudo apt-get update
  - sudo apt-get install -y check
   
compiler:
  - gcc
  
script:
  - echo "running tests"
  - make
  - make test
